QLBGD/Areas/Admin/Controllers/NhanHieuAController.cs
using QLBGD.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QLBGD.Areas.Admin.Controllers
{
    public class NhanHieuAController : Controller
    {
        private QuanLyBanGiayDep1Entities db = new QuanLyBanGiayDep1Entities();

        // lấy mã nhãn hiệu
        string LayMaNH()
        {
            var maMax = db.NhanHieux.ToList().Select(n => n.MaNhanHieu).Max();
            int maNH = int.Parse(maMax.Substring(2)) + 1;
            string NH = String.Concat("00", maNH.ToString());
            return "NH" + NH.Substring(maNH.ToString().Length - 1);
        }

        // GET: Admin/NhanHieuA
        public ActionResult Index()
        {
            return View(db.NhanHieux.ToList());
        }

        // GET: Admin/NhanHieuA/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanHieu nhanHieu = db.NhanHieux.Find(id);
            if (nhanHieu == null)
            {
                return HttpNotFound();
            }
            return View(nhanHieu);
        }

        // GET: Admin/NhanHieuA/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.MaNH = LayMaNH();
            return View();
        }

        // POST: Admin/NhanHieuA/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNhanHieu,TenNhanHieu,GhiChu,AnhNH")] NhanHieu nhanHieu)
        {
            //System.Web.HttpPostedFileBase Avatar;
            var imgNH = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgNH.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/brands/" + postedFileName); //
            imgNH.SaveAs(path); //

            if (ModelState.IsValid)
            {
                nhanHieu.MaNhanHieu = LayMaNH();
                nhanHieu.AnhNH = postedFileName;
                db.NhanHieux.Add(nhanHieu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNH = LayMaNH();
            return View(nhanHieu);
        }

        // GET: Admin/NhanHieuA/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanHieu nhanHieu = db.NhanHieux.Find(id);
            if (nhanHieu == null)
            {
                return HttpNotFound();
            }
            return View(nhanHieu);
        }

        // POST: Admin/NhanHieuA/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNhanHieu,TenNhanHieu,GhiChu,AnhNH")] NhanHieu nhanHieu)
        {
            var imgNH = Request.Files["Avatar"];
            try
            {
                //Lấy thông tin từ input type=file có tên Avatar
                string postedFileName = System.IO.Path.GetFileName(imgNH.FileName);
                //Lưu hình đại diện về Server
                var path = Server.MapPath("/Images/brands/" + postedFileName);
                imgNH.SaveAs(path);
            }
            catch
            { }
            if (ModelState.IsValid)
            {
                db.Entry(nhanHieu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhanHieu);
        }

        // GET: Admin/NhanHieuA/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanHieu nhanHieu = db.NhanHieux.Find(id);
            if (nhanHieu == null)
            {
                return HttpNotFound();
            }
            return View(nhanHieu);
        }

        // POST: Admin/NhanHieuA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NhanHieu nhanHieu = db.NhanHieux.Find(id);
            db.NhanHieux.Remove(nhanHieu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLBGD/Areas/Admin/Views/NhanHieuA/Create.cshtml
@model QLBGD.Models.NhanHieu

@{
    ViewBag.Title = "Thêm mới nhãn hiệu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm mới một nhãn hiệu</h2>

@using (Html.BeginForm("Create", "NhanHieuA", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaNhanHieu, "Mã nhãn hiệu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaNH" disabled readonly class="form-control col-md-4" />
                @*@Html.EditorFor(model => model.MaNhanHieu, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.MaNhanHieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNhanHieu, "Tên nhãn hiệu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNhanHieu, new { htmlAttributes = new { @class = "form-control col-md-4" } })
                @Html.ValidationMessageFor(model => model.TenNhanHieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control col-md-4" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.AnhNH, "Ảnh nhãn hiệu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.AnhNH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLBGD/Areas/Admin/Views/NhanHieuA/Delete.cshtml
@model QLBGD.Models.NhanHieu

@{
    ViewBag.Title = "Xóa nhãn hiệu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<h4 style="color:red;"> Bạn có chắc chắn xóa thông tin này?</h4>
<div>
    <hr />
    <div class="row">
        <div class="col-md-2">
            <img width="200px" height="200px" style="border-radius:50%;margin-left:30px;margin-top:20px;" src="~/Images/brands/@Html.DisplayFor(model => model.AnhNH)" />
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-9">
            <div>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Tên nhãn hiệu
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenNhanHieu)
                    </dd>

                    <dt>
                        Ghi chú
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GhiChu)
                    </dd>

                    <dt>
                        Ảnh nhãn hiệu
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AnhNH)
                    </dd>

                </dl>
            </div>

        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLBGD/Areas/Admin/Views/NhanHieuA/Details.cshtml
@model QLBGD.Models.NhanHieu

@{
    ViewBag.Title = "Xem chi tiết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<h2>Thông tin chi tiết</h2>

<div>
    <hr />
    <div class="row">
        <div class="col-md-2">
            <img width="250px" height="250px" style="border-radius: 5%; margin-left: 30px; margin-top: 20px; margin-bottom: 20px; border: 1px solid #2F4F4F" src="~/Images/brands/@Html.DisplayFor(model => model.AnhNH)" />
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-9">
            <div>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Tên nhãn hiệu
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenNhanHieu)
                    </dd>

                    <dt>
                        Ghi chú
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GhiChu)
                    </dd>

                  

                </dl>
            </div>
            <p style="padding-top: 30px">
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaNhanHieu }) |
                @Html.ActionLink("Xóa", "Delete", new { id = Model.MaNhanHieu }) |
                @Html.ActionLink("Quay lại", "Index")
            </p>
        </div>
    </div>
</div>

@Html.Partial("_SanPhamPartial", Model.SanPhams)

QLBGD/Areas/Admin/Views/NhanHieuA/Edit.cshtml
@model QLBGD.Models.NhanHieu

@{
    ViewBag.Title = "Cập nhật thông tin hàng hóa";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            var fileupload = $("#Avatar");
            var image = $("#FileUpload");
            image.click(function () {
                fileupload.click();
            });
            fileupload.change(function () {
                var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
                document.getElementById("AnhNH").value = fileName;
            });
        });
    </script>
}

<h3>Chỉnh sửa</h3>

@using (Html.BeginForm("Edit", "NhanHieuA", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNhanHieu)

        <div class="form-group">
            @Html.LabelFor(model => model.TenNhanHieu, "Tên nhãn hiệu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNhanHieu, new { htmlAttributes = new { @class = "form-control col-md-4" } })
                @Html.ValidationMessageFor(model => model.TenNhanHieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control col-md-4" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.AnhNH, "Ảnh nhãn hiệu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNH, new { htmlAttributes = new { @class = "form-control col-md-4" } })
                @Html.ValidationMessageFor(model => model.AnhNH, "", new { @class = "text-danger" })
                <input type="file" name="Avatar" id="Avatar" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLBGD/Areas/Admin/Views/NhanHieuA/Index.cshtml
@model IEnumerable<QLBGD.Models.NhanHieu>

@{
    ViewBag.Title = "Danh sách nhãn hiệu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int i = 0;
}


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Nhãn hiệu
    </div>
    <p>
        @Html.ActionLink("Tạo mới", "Create")
    </p>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr style="background-color: #778899;">
                        <th>
                            Số thứ tự
                        </th>
                        <th>
                            Tên nhãn hiệu
                        </th>
                        <th>
                            Ghi chú
                        </th>
                        <th>
                            Ảnh nhãn hiệu
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @{i++;}
                                @i
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenNhanHieu)
                            </td>
                            <td style="width:500px;">
                                @Html.DisplayFor(modelItem => item.GhiChu)
                            </td>
                            <td style="width: 260px;">
                                <img src="~/Images/brands/@Html.DisplayFor(modelItem => item.AnhNH)" width="250" height="250" />
                            </td>
                            <td>
                                @Html.ActionLink("Xem chi tiết", "Details", new { id = item.MaNhanHieu })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>