QLBGD/Areas/Admin/Controllers/KhachHangAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CryptoLib;
using QLBGD.Models;

namespace QLBGD.Areas.Admin.Controllers
{
    public class KhachHangAController : Controller
    {
        private QuanLyBanGiayDep1Entities db = new QuanLyBanGiayDep1Entities();

        // lấy mã khách hàng tự động
        string LayMaKhachHang()
        {
            var maMax = db.KhachHangs.ToList().Select(n => n.MaKhachHang).Max();
            int maKhachHang = int.Parse(maMax.Substring(2)) + 1;
            string KH = String.Concat("000", maKhachHang.ToString());
            return "KH" + KH.Substring(maKhachHang.ToString().Length - 1);
        }

        // GET: Admin/KhachHangA
        // tìm kiếm
        [HttpGet]
        public ActionResult Index(string maKH = "", string hoTen = "", string gioiTinh = "", string soDienThoai = "", string email = "", string tinhThanh = "", string diaChi = "")
        {
            ViewBag.maKhachHang = maKH;
            ViewBag.hoTen = hoTen;

            bool nam = true;
            bool nu = false;
            ViewBag.gioiTinh = null;

            if (gioiTinh == "1")
            {
                nu = true;
                ViewBag.gioiTinh = "1";
            }
            else if (gioiTinh == "0")
            {
                nam = false;
                ViewBag.gioiTinh = "0";
            }

            ViewBag.SoDienThoai = soDienThoai;
            ViewBag.Email = email;
            ViewBag.TinhThanh = tinhThanh;
            ViewBag.DiaChi = diaChi;

            var khachHangs = db.KhachHangs.Where(kh => kh.MaKhachHang.Contains(maKH) &&
                                                (kh.Ho + " " + kh.Ten).Contains(hoTen) &&
                                                (kh.GioiTinh == nam || kh.GioiTinh == nu) &&
                                                kh.SDT.Contains(soDienThoai) &&
                                                kh.Email.Contains(email) &&
                                                kh.TinhOrTP.Contains(tinhThanh) &&
                                                kh.DiaChi.Contains(diaChi));

            if (khachHangs.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";

            return View(khachHangs.ToList());
        }

        // GET: Admin/KhachHangA/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: Admin/KhachHangA/Create
        public ActionResult Create()
        {
            ViewBag.MaKhachHang = LayMaKhachHang();
            return View();
        }

        // POST: Admin/KhachHangA/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKhachHang,Ho,Ten,GioiTinh,SDT,Email,MatKhau,TinhOrTP,DiaChi")] KhachHang khachHang)
        {

            if (ModelState.IsValid)
            {
                khachHang.MaKhachHang = LayMaKhachHang();
                khachHang.MatKhau = Encryptor.MD5Hash(khachHang.MatKhau);

                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKhachHang = LayMaKhachHang();
            return View(khachHang);
        }

        // GET: Admin/KhachHangA/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: Admin/KhachHangA/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKhachHang,Ho,Ten,GioiTinh,SDT,Email,MatKhau,TinhOrTP,DiaChi")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khachHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }

        // GET: Admin/KhachHangA/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: Admin/KhachHangA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLBGD/Areas/Admin/Views/KhachHangA/Create.cshtml
@model QLBGD.Models.KhachHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>KhachHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaKhachHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MaKhachHang, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="text" value="@ViewBag.MaKhachHang" disabled readonly class="form-control" />
                @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhOrTP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhOrTP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhOrTP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLBGD/Areas/Admin/Views/KhachHangA/Delete.cshtml
@model QLBGD.Models.KhachHang

@{
    ViewBag.Title = "Xóa khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h3 style="color: orangered">Bạn có chắc muốn xóa khách hàng này?</h3>

<div class="row">
    <hr />
    <div class="col-md-11">
        <dl class="dl-horizontal">
            <dt style="height:40px;font-size:30px;">
                @Html.DisplayFor(model => model.Ho) @Html.DisplayFor(model => model.Ten)
            </dt>

        
            <dt>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>

            <dd>
                @{ var gtinh = "";
                    if (Model.GioiTinh == true)
                    { gtinh = "Nam"; }
                    else
                    { gtinh = "Nữ"; }
                }
                @gtinh
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MatKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MatKhau)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TinhOrTP)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TinhOrTP)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

        </dl>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-danger" /> |
                @Html.ActionLink("Quay lại", "Index")
            </div>
        }
    </div>

   
</div>

QLBGD/Areas/Admin/Views/KhachHangA/Details.cshtml
@model QLBGD.Models.KhachHang

@{
    ViewBag.Title = "Thông tin khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin khách hàng</h2>

<div class="row">
    <hr />
    <div class="col-md-1">

    </div>
    <div class="col-md-11">
        <dl class="dl-horizontal">
            <dt style="height:40px;font-size:30px;">
                @Html.DisplayFor(model => model.Ho) @Html.DisplayFor(model => model.Ten)
            </dt>

            <dt>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>

            <dd>
                @{ var gtinh = "";
                    if (Model.GioiTinh == true)
                    { gtinh = "Nam"; }
                    else
                    { gtinh = "Nữ"; }
                }
                @gtinh
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MatKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MatKhau)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TinhOrTP)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TinhOrTP)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

        </dl>
    </div>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaKhachHang }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

QLBGD/Areas/Admin/Views/KhachHangA/Edit.cshtml
@model QLBGD.Models.KhachHang

@{
    ViewBag.Title = "Cập nhật thông tin khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Cập nhật thông tin khách hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKhachHang)

        <div class="form-group">
            @Html.LabelFor(model => model.Ho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">

                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhOrTP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhOrTP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhOrTP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLBGD/Areas/Admin/Views/KhachHangA/Index.cshtml
@model IEnumerable<QLBGD.Models.KhachHang>

@{
    ViewBag.Title = "Danh sách khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenNV", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <h3>Danh sách khách hàng</h3>
    <div>
        @using (Html.BeginForm("Index", "KhachHangA", FormMethod.Get))
        {
            @Html.AntiForgeryToken()


            <table class="table1" align="center">
                <tr>
                    <td>
                        <div>Mã khách hàng</div>
                    </td>
                    <td>
                        <input type="text" name="maKH" value="@ViewBag.maKhachHang" />
                    </td>

                </tr>
                <tr>
                    <td>Họ tên</td>
                    <td>
                        <input type="text" name="hoTen" value="@ViewBag.hoTen" />
                    </td>

                </tr>

                <tr>
                    <td>Giới tính</td>
                    <td>
                        @if (@ViewBag.gioiTinh == null)
                        {
                            <input type="radio" name="gioiTinh" value="1" /><text>Nam</text>
                            <input type="radio" name="gioiTinh" value="0" /><text>Nữ</text>
                        }
                        else if (@ViewBag.gioiTinh == "1")
                        {
                            <input type="radio" name="gioiTinh" checked value="1" /><text>Nam</text>
                            <input type="radio" name="gioiTinh" value="0" /><text>Nữ</text>
                        }
                        else
                        {
                            <input type="radio" name="gioiTinh" value="1" /><text>Nam</text>
                            <input type="radio" name="gioiTinh" checked value="0" /><text>Nữ</text>
                        }


                    </td>

                </tr>
                <tr>
                    <td>Số điện thoại</td>
                    <td>
                        <input type="text" name="soDienThoai" value="@ViewBag.SoDienThoai" />
                    </td>

                </tr>

                <tr>
                    <td>Email</td>
                    <td>
                        <input type="text" name="email" value="@ViewBag.Email" />
                    </td>
                </tr>

                <tr>
                    <td>Tỉnh thành</td>
                    <td>
                        <input type="text" name="tinhThanh" value="@ViewBag.TinhThanh" />
                    </td>
                </tr>

                <tr>
                    <td>Địa chỉ</td>
                    <td>
                        <input type="text" name="diaChi" value="@ViewBag.DiaChi" />
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
				background-color: blue;color:white" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
				background-color: blue;color:white" onclick="location.href='@Url.Action("Index", "KhachHangA")'" />

                    </td>
                </tr>
            </table>
        }
    </div>


    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
        //Số dòng
        grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaKhachHang","Mã khách hàng"), //the model fields to display
        grid.Column("Ho","Họ"),
        grid.Column("Ten","Tên"  ),
        grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
        grid.Column("SDT","Số điện thoại"  ),
        grid.Column("Email","Email"  ),
        grid.Column("MatKhau","Mật khẩu"  ),
        grid.Column("TinhOrTp","Tỉnh thành"  ),
        grid.Column("DiaChi","Địa chỉ"  ),
    grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                        new { id = item.MaKhachHang})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><i class="bi bi-pencil"></i></abbr></a>
    <a href="@Url.Action("Details",
                        new { id = item.MaKhachHang})" class="edit-btn"><abbr title="Xem chi tiết"><i class="bi bi-briefcase"></i></abbr></a>
    <a href="@Url.Action("Delete",
                        new { id = item.MaKhachHang})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <i class="bi bi-file-earmark-x"></i>
        </abbr>
    </a>
    </text>),

}
)
    </div>
</body>
</html>