QLBGD/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLBGD.Models;

namespace QLBGD.Controllers
{
    public class SanPhamsController : Controller
    {
        private QuanLyBanGiayDep1Entities db = new QuanLyBanGiayDep1Entities();

        // GET: SanPhams
        public ActionResult Index(string maSP = "", string tenSP = "", string maLSP = "", string maNH = "",
                                  string MauSac = "", string giaMin = "", string giaMax = "",
                                  string tinhTrang = "")
        {
            ViewBag.maSP = maSP;
            ViewBag.tenSP = tenSP;

            ViewBag.MaLSP = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNH = new SelectList(db.NhanHieux, "MaNhanHieu", "TenNhanHieu");

            ViewBag.MauSac = MauSac;

            int min = 0, max = Int32.MaxValue;

            if (giaMin == "")
            {
                ViewBag.GiaMin = "";
                min = 0;
            }
            else
            {
                ViewBag.GiaMin = giaMin;
                min = int.Parse(giaMin);
            }
            if (giaMax == "")
            {
                max = Int32.MaxValue;
                ViewBag.GiaMax = "";
            }
            else
            {
                ViewBag.GiaMax = giaMax;
                max = int.Parse(giaMax);
            }

            ViewBag.TinhTrang = tinhTrang;

            var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham).Include(s => s.NhanHieu)
                                      .Where(sp => sp.MaSanPham.Contains(maSP) &&
                                                    sp.TenSanPham.Contains(tenSP) &&
                                                    sp.MaLoaiSanPham.Contains(maLSP) &&
                                                    sp.MaNhanHieu.Contains(maNH) &&
                                                    sp.MauSac.Contains(MauSac) &&
                                                    sp.DonGia >= min && sp.DonGia <= max &&
                                                    sp.TinhTrang.Contains(tinhTrang));

            if (sanPhams.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(sanPhams.ToList());
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhanHieu = new SelectList(db.NhanHieux, "MaNhanHieu", "TenNhanHieu");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,TenSanPham,MaNhanHieu,MaLoaiSanPham,MauSac,KichThuoc,DonGia,TinhTrang,MoTa,AnhSP,GioiTinh")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.MaNhanHieu = new SelectList(db.NhanHieux, "MaNhanHieu", "TenNhanHieu", sanPham.MaNhanHieu);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.MaNhanHieu = new SelectList(db.NhanHieux, "MaNhanHieu", "TenNhanHieu", sanPham.MaNhanHieu);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,TenSanPham,MaNhanHieu,MaLoaiSanPham,MauSac,KichThuoc,DonGia,TinhTrang,MoTa,AnhSP,GioiTinh")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.MaNhanHieu = new SelectList(db.NhanHieux, "MaNhanHieu", "TenNhanHieu", sanPham.MaNhanHieu);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLBGD/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLBGD.Models;

namespace QLBGD.Controllers
{
    public class TrangChuController : Controller
    {
        private QuanLyBanGiayDep1Entities db = new QuanLyBanGiayDep1Entities();

        // GET: TrangChu
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham).Include(s => s.NhanHieu);
            return View(sanPhams);
        }
        public ActionResult About()
        {
            return View();
        }
    }
}

QLBGD/Views/TrangChu/About.cshtml
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
    ViewBag.Title = "Thông tin về cửa hàng";
}

<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
<style>


    .bgimg {
        background-position: center;
        background-size: cover;
        background-image: url("/w3images/coffeehouse.jpg");
        min-height: 75%;
    }

    .menu {
        display: none;
    }
</style>
<body>


    <!-- Add a background color and large text to the whole page -->
    <div class="w3-sand w3-grayscale w3-large">
        
        <!-- About Container -->
        <div class="w3-container" id="about">
            <div class="w3-content" style="max-width:700px">
                <h5 class="w3-center w3-padding-64"><span class="w3-tag w3-wide">Thông tin về cửa hàng</span></h5>
                <p>“Bạn sẽ khó có nhiều thời gian để chăm chút cho sự lựa chọn giày dép. Có quá nhiều người nghĩ rằng giày dép không quan trọng, nhưng toàn bộ sự tinh tế của ta toát ra chính từ đôi chân.”.</p>
                <p> Christian Dior  </p>
                <p>“Một đôi giày có thể thay đổi cuộc đời bạn.”.</p>
                <p>Cinderella</p>
                <div class="w3-panel w3-leftbar w3-light-grey">
                    <p><i>Danh ngôn về thời trang</i></p>
                </div>
                <img src="~/Images/myShop.png" style="width:100%;max-width:1000px" class="w3-margin-top"
                <p><strong>Cửa hàng:</strong> FS Sneakers Nha Trang</p>
                <p><strong>Giờ mở cửa:</strong> mỗi ngày từ 6 giờ sáng đến 21 giờ tối.</p>
                <p><strong>Địa chỉ:</strong> Số 124, Nguyễn Đình Chiểu</p>
            </div>
        </div>
      </div>



        <!-- Footer -->
        <footer class="w3-center w3-light-grey w3-padding-48 w3-large">
            <p><a href="#!" class="w3-hover-text-green">Trân trọng!</a></p>
        </footer>

        <script>
            // Tabbed Menu
            function openMenu(evt, menuName) {
                var i, x, tablinks;
                x = document.getElementsByClassName("menu");
                for (i = 0; i < x.length; i++) {
                    x[i].style.display = "none";
                }
                tablinks = document.getElementsByClassName("tablink");
                for (i = 0; i < x.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" w3-dark-grey", "");
                }
                document.getElementById(menuName).style.display = "block";
                evt.currentTarget.firstElementChild.className += " w3-dark-grey";
            }
            document.getElementById("myLink").click();
        </script>

</body>
</html>

QLBGD/Views/TrangChu/Index.cshtml
@model IEnumerable<QLBGD.Models.SanPham>

@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
    ViewBag.Title = "Trang chủ";
}
<style>
    .donGia {
        color: crimson;
        font-weight: bold;
    }

    .a1 {
        color: dimgrey;
        font-weight: 600;
    }

        .a1:hover {
            background-color: #F5F5F5;
            color: black;
            text-decoration: none;
            font-weight: 700;
            text-align: center;
            border: 1px solid #2F4F4F;
            border-radius: 5px;
            filter: drop-shadow(0 0 2px black);
        }

    .tt {
        font-weight: 750;
    }

    .d1 {
        margin: 0px;
        padding: 5px;
    }

        .d1:hover {
            filter: drop-shadow(0 0 5px blue);
            border-radius: 1%;
            padding: 0;
        }

    input[type=submit] {
        margin: 5px;
    }

    small {
        color: #FDD017;
        font-size: 20px;
    }

    a:hover {
        text-decoration: none;
    }

    .list-group-item {
        border-right: none;
        border-left: none;
    }
</style>
<div class="row">
    <div class="col-lg-2">
        <h5 class="my-4 tt">Thương hiệu nổi tiếng</h5>
        <div class="list-group">
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH001"})">
                ASICS
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH002"})">
                HOKA
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH003"})">
                MIZUNO
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH004"})">
                NEW BALANCE
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH005"})">
                SKECHERS
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH006"})">
                ADIDAS
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH007"})">
                UNDER ARMOUR
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH008"})">
                ELLESSE
            </a>
            <a class="list-group-item a1" href="@Url.Action("Details", "NhanHieus", new { @id = "NH009"})">
                FILA
            </a>
        </div>
    </div>
    <div class="col-lg-10">
        <div class="carousel slide my-4" id="carouselExampleIndicators" data-ride="carousel">
            <ol class="carousel-indicators">
                <li class="active" data-target="#carouselExampleIndicators" data-slide-to="0"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active"><img class="d-block img-fluid" src="~/Images/contents/a.jpg" alt="First slide" style="border-radius:10px;" /></div>
                <div class="carousel-item"><img class="d-block img-fluid" src="~/Images/contents/b.jpg" alt="Second slide" style="border-radius:10px;" /></div>
                <div class="carousel-item"><img class="d-block img-fluid" src="~/Images/contents/c.jpg" alt="Third slide" style="border-radius:10px;" /></div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <p class="h3 tt">Giày thời trang</p>
        <hr />
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.MaLoaiSanPham.Contains("LSP001"))
                {
                    <div class="mb-3 d1  col-3 ">
                        <div class="card h-100">
                            <a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})">
                                <img class="card-img-top" src="~/Images/products/@Html.DisplayFor(modelItem => item.AnhSP)" alt="..." width="200" height="300px" />
                            </a>

                            <div class="card-body">
                                <h4 class="card-title"><a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})" class="text-dark">@Html.DisplayFor(modelItem => item.TenSanPham)</a></h4>
                                <h5 class="donGia">@String.Format("{0:0,0}", item.DonGia) VND</h5>
                                <p class="card-text font-weight-bold">@Html.DisplayFor(modelItem => item.TinhTrang)</p>
                            </div>
                            <div class="card-footer"><small>★ ★ ★ ★ ☆</small></div>
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @cMaSanPham = item.MaSanPham, @strURL = Request.Url.ToString() }))
                            {
                                <input type="submit" style="cursor:pointer" value="Thêm vào giỏ hàng" class="btn btn-danger" />
                            }
                        </div>
                    </div>
                }
            }
        </div>

        <p class="h3 tt">Giày xăng đan</p>
        <hr />
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.MaLoaiSanPham.Contains("LSP002"))
                {
                    <div class="mb-3 d1  col-3 ">
                        <div class="card h-100">
                            <a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})">
                                <img class="card-img-top" src="~/Images/products/@Html.DisplayFor(modelItem => item.AnhSP)" alt="..." width="200" height="300px" />
                            </a>
                            <div class="card-body">
                                <h4 class="card-title"><a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})" class="text-dark">@Html.DisplayFor(modelItem => item.TenSanPham)</a></h4>
                                <h5 class="donGia">@String.Format("{0:0,0}", item.DonGia) VND</h5>
                                <p class="card-text font-weight-bold">@Html.DisplayFor(modelItem => item.TinhTrang)</p>
                            </div>
                            <div class="card-footer"><small>★ ★ ★ ★ ☆</small></div>
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @cMaSanPham = item.MaSanPham, @strURL = Request.Url.ToString() }))
                            {
                                <input type="submit" style="cursor:pointer" value="Thêm vào giỏ hàng" class="btn btn-danger" />
                            }
                        </div>
                    </div>
                }
            }
        </div>

        <p class="h3 tt">Giày thể thao</p>
        <hr />
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.MaLoaiSanPham.Contains("LSP003"))
                {
                    <div class="mb-3 d1  col-3 ">
                        <div class="card h-100">
                            <a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})">
                                <img class="card-img-top" src="~/Images/products/@Html.DisplayFor(modelItem => item.AnhSP)" alt="..." width="200" height="300px" />
                            </a>
                            <div class="card-body">
                                <h4 class="card-title"><a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})" class="text-dark">@Html.DisplayFor(modelItem => item.TenSanPham)</a></h4>
                                <h5 class="donGia">@String.Format("{0:0,0}", item.DonGia) VND</h5>
                                <p class="card-text font-weight-bold">@Html.DisplayFor(modelItem => item.TinhTrang)</p>
                            </div>
                            <div class="card-footer"><small>★ ★ ★ ★ ☆</small></div>
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @cMaSanPham = item.MaSanPham, @strURL = Request.Url.ToString() }))
                            {
                                <input type="submit" style="cursor:pointer" value="Thêm vào giỏ hàng" class="btn btn-danger" />
                            }
                        </div>
                    </div>
                }
            }
        </div>

        <p class="h3 tt">Dép thời trang</p>
        <hr />
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.MaLoaiSanPham.Contains("LSP004"))
                {
                    <div class="mb-3 d1  col-3 ">
                        <div class="card h-100">
                            <a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})">
                                <img class="card-img-top" src="~/Images/products/@Html.DisplayFor(modelItem => item.AnhSP)" alt="..." width="200" height="300px" />
                            </a>
                            <div class="card-body">
                                <h4 class="card-title"><a href="@Url.Action("Details", "SanPhams", new { @id = item.MaSanPham})" class="text-dark">@Html.DisplayFor(modelItem => item.TenSanPham)</a></h4>
                                <h5 class="donGia">@String.Format("{0:0,0}", item.DonGia) VND</h5>
                                <p class="card-text font-weight-bold">@Html.DisplayFor(modelItem => item.TinhTrang)</p>
                            </div>
                            <div class="card-footer"><small>★ ★ ★ ★ ☆</small></div>
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @cMaSanPham = item.MaSanPham, @strURL = Request.Url.ToString() }))
                            {
                                <input type="submit" style="cursor:pointer" value="Thêm vào giỏ hàng" class="btn btn-danger" />
                            }
                        </div>
                    </div>
                }
            }
        </div>

    </div>

</div>